# site information
authors: "The League of Space Hackers"
description: "Current information on the scientific probes sent into deep space by human beings of planet Earth"
twitter: spaceprob_es


# jekyll stuff:
permalink: /:title/
exclude: [README.markdown, Makefile]
highlighter: null
timezone: UTC
encoding: utf-8
baseurl: /
